CREATE TABLE SensorData (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    umi VARCHAR(30) NOT NULL,
    temp VARCHAR(30) NOT NULL,
    lumi VARCHAR(10),
    hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
